### ISSUE TITLE
Doesn't work with newer Zig

### ISSUE THREAD

**Issue by jdjohnston** [BrookJeynes/zig-shared-memory#1]
First, I want to say that this is a very nice example and well explained on the video. Thanks!
Being new to `Zig`, but not programming or shared-memory, I wanted to build it for myself. That's when I ran into problems.

Environment: I'm using `Zig 0.12.0-dev.2750+5f9255829` on `EndeavourOS`.

You don't actually specify which version of `Zig` that you are using. I imagine you are aware that `Zig` is essentially a moving target. I like how `ziglings.org` specifiy the minimal version of `Zig` in both their `README.md` & the `build.zig` will err out if the requirement isn't met. That might be overkill for a simple example, but specifying it in either the `README` or during the video or in the show notes, or ... :). I imagine you get my point.

On the more technical side:
- Newer `zig` won't build since `buld.zig` refers to the non-existent `src/root.zig` on line 22. So does line 70, but that didn't prevent building.
- `std.os.mmap` no longer takes a bitset for the fourth argument. It now takes a struct, which can be an anonymous struct. A good example usage is in `std/heap/PageAllocator.zig`. I _think_ this is an improvement for `os.mmap`.

**Comment by BrookJeynes** [comment]
Hey @jdjohnston!

> You don't actually specify which version of Zig that you are using.

My bad 😅 You make a good point here. I've now specified the latest working version in both the README and `build.zig.zon`

> Newer zig won't build since buld.zig refers to the non-existent src/root.zig

Whoops! I must've forgotten to clean up that part. Should be all fixed now!

> `std.os.mmap` no longer takes a bitset for the fourth argument. It now takes a struct, which can be an anonymous struct. 

Nice catch, should be all fixed now!

You can find the changes here: https://github.com/BrookJeynes/zig-shared-memory/commit/a749e16c9ad610d62ef0396b2bd535a195c7c289

I've also added an ERRATA comment to the video with these changes, appreciate it :)
